apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app-v2
  template:
    metadata:
      labels:
        app: weather-app-v2
        track: stable
    spec:
      containers:
        - name: weather-app-v2
          image: "gcr.io/laboratorio-ucloud-01/weather-app:latest"
          ports:
          - name: http1
            containerPort: 8080
          imagePullPolicy: Always